version: '3'
services:
  api:
    build: ./api
    image: amichaitr/restapi-pg-db
    container_name: api
    ports:
      - "5000:5000"
    depends_on:
      - "pg_db"
    command: ["python", "./api/v1/api.py"]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3

  pg_db:
    build: ./pg_db
    image: amichaitr/postgres
    container_name: pg_db
  
